language: java
deploy:
  provider: cloudfoundry
  username: sivanathan011198@gmail.com
  password: Sivanathan1998@
  api: https://api.run.pivotal.io
  organization: Shipspring
  space: development
  manifest: manifest.yml
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
